### ISSUE TITLE
Reorganization documentation issues

### ISSUE THREAD

**Issue by margaretkennedy** [deephaven/deephaven-docs-community#256]
- [x] Rename "Install and run Deephaven natively"
- [x] Organize reference section 
- [ ] Rewrite pip install guide (https://github.com/deephaven/deephaven-docs-community/issues/242)
- [ ] Quickstart pip section (https://github.com/deephaven/deephaven-docs-community/issues/257)
- [x] Create tables guide is incomplete (https://github.com/deephaven/deephaven-docs-community/issues/258)
- [x] Replay static data -- does this belong under table creation?
